In [2]:
import numpy as np

state = {
    0 : "Rest",
    1 : "Exercises",
    2 : "Sweeties"
}

A = [
    [0.2, 0.6, 0.2],
    [0.1, 0.6, 0.3],
    [0.2, 0.7, 0.1]
]

1. The starting state is rest. Calculate the probability of possible activity on the 15th day.

In [17]:
def calculate(A, days):
    A_n = A
    for i in range(days):
        A_n = np.matmul(A_n, A)
        
    return A_n

result = calculate(A, 15)
print(result)
print('\nThe possibility of exercise on day 15 is', end=' ')
print('{:.2f}%'.format(result[0][1] * float(100)))

[[0.13761468 0.62385321 0.23853211]
 [0.13761468 0.62385321 0.23853211]
 [0.13761468 0.62385321 0.23853211]]

The possibility of exercise on day 15 is 62.39%


2. What about the state and probability after 10000 days?

In [18]:
result = calculate(A, 10000)
print(result)
print('\nThe possibility of exercise on day 10,000 is', end=' ')
print('{:.2f}%'.format(result[0][1] * float(100)))

[[0.13761468 0.62385321 0.23853211]
 [0.13761468 0.62385321 0.23853211]
 [0.13761468 0.62385321 0.23853211]]

The possibility of exercise on day 10,000 is 62.39%


3. What do you observe from the above two?

The values have stayed the same. This indicates that this is what the probabilities converge to as we take this simulation further and further out. Meaning this is exactly what the probabilities are.